### ISSUE TITLE
Issue Overwriting Calibration

### ISSUE THREAD

**Issue by sminogue** [adafruit/Adafruit_Sensor_Calibration#5]
Summary:
Adafruit_Sensor_Calibration_SDFat.saveCalibration fails to overwrite existing calibrations if they exist. Also the failure is silent and does not result in any kind of error. Save appears to have worked but no changes to the filesystem are made.

Background:
So I am attempting to perform calibration on a sensor. When I use Adafruit_Sensor_Calibration_SDFat.saveCalibration on a freshly formatted file system it works perfectly. However, my code needs to allow a user to update calibrations as my device travels long distances.

To this end I created a calibration function which when complete attempts to save to filesystem the newly updated calibration... saveCalibration returns true leading me to believe that the filesystem has been updated. However subsequent calls to display the saved calibration reveal the original calibration is still on filesystem.

Suggested Solutions:
1. If this code is behaving correctly in that it should not overwrite an existing calibration. Then at the very least this save function should return false or throw an exception so the calling code can handle the error.

2. If 1 ^^ then there should be a separate function to allow us to overwrite or permanently update the calibration. I found an old forum thread about this and the poster was attempting to manually delete the file before calling this save function to get around the problem. He was given some small note about degrading performance of the FAT filesystem but no information how to properly avoid it.

3. Update Adafruit_Sensor_Calibration_SDFat.saveCalibration to overwrite. From thread: https://stackoverflow.com/questions/23092040/how-to-open-a-file-which-overwrite-existing-content this appears to be doable by adding the "O_TRUNC" flag to line 99.

So:
`File file = theFS->open(_cal_filename, O_WRITE | O_CREAT);`

Becomes:
`File file = theFS->open(_cal_filename, O_WRITE | O_CREAT | O_TRUNC);`

**Comment by ladyada** [comment]
ooh could you submit a PR please - thank you :)
