### ISSUE TITLE
Support for magnetic field

### ISSUE THREAD

**Issue by alvaro-oliver** [adafruit/Adafruit_Sensor_Calibration#8]
Please add support for mag_field on saveCalibration() and loadCalibration() methods.

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_Sensor_Calibration/blob/37607fd6a714bb5fd8611dc86cf01b5bf88d96a1/Adafruit_Sensor_Calibration_EEPROM.cpp#L34
?

**Comment by alvaro-oliver** [comment]
Ok, I can see it is implemented for EEPROM but I think is not the case for SDFat.

**Comment by ladyada** [comment]
ah, ok! wanna try submitting a PR? it just needs another JSON entry!

**Comment by alvaro-oliver** [comment]
Sure, just give me a few more days.

**Comment by ladyada** [comment]
yayy!
